<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.minmq</groupId>
        <artifactId>min-mq</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>min-mq-example</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.minmq</groupId>
            <artifactId>min-mq-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.minmq</groupId>
            <artifactId>min-mq-broker</artifactId>
        </dependency>
        <dependency>
            <groupId>com.minmq</groupId>
            <artifactId>min-mq-broker</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.minmq</groupId>
            <artifactId>min-mq-client</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <!-- Protobuf 运行时 -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.25.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>3.11.4</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <protocVersion>3.25.3</protocVersion> <!-- 指定protoc版本 -->
                            <inputDirectories>
                                <include>src/main/proto</include> <!-- proto文件路径 -->
                            </inputDirectories>
                            <outputTargets>
                                <outputTarget>
                                    <type>java</type>
                                    <outputDirectory>target/generated-sources/protobuf/java</outputDirectory>
                                </outputTarget>
                            </outputTargets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <mainClass>com.minmq.example.ExampleBrokerMain</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>